name: Deploy to cPanel

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan yourdomain.com >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r ./your-project-folder/ username@yourdomain.com:/home/username/public_html/your-folder/
